### PR TITLE
HA 2024.2 update

### PR DESCRIPTION
**Pull request by raulgbcr**
Add light color modes from the 2024.2 update
Moved effects to const

### CODE REVIEW

**Comment by raulgbcr** [comment]
@8none1 Hey Will! Mind testing this whenever you have some free time? Looks good to me!

Context: https://developers.home-assistant.io/blog/2024/01/23/light-color-mode-changes/

**Comment by 8none1** [comment]
Ah! This is a nice improvement.  Looks good, but I'll test it now...

**Comment by 8none1** [comment]
To test this I did:
 - Upgrade Home Assistant docker to the latest stable
 - Removed all the old devices
 - Checkout the branch locally and copy the lednetwf_ble directory over to HA & restart
 -  Readded one device to test
 - The device was automatically discovered and configured :heavy_check_mark: 
 - The device could turn on and off :heavy_check_mark: 
 - The brightness of a static single colour could be adjusted :heavy_check_mark: 
 - The brightness of a white mode could be adjusted :heavy_check_mark: 
 - The brightness of effects could be adjusted :heavy_check_mark: 

So it all looks good to me!

:+1:  Feel free to merge

**Review by 8none1 — APPROVED** [review]
Tested and approved.

**Pull request merged**
