### PR TITLE
HA 2025.3 deprecated warning fix

### LINKED ISSUE #22: Invalid supported color modes
The latest version (not yet released) triggers this error:

```
2024-06-21 15:22:03.265 WARNING (MainThread) [homeassistant.components.light] None (<class 'custom_components.lednetwf_ble.light.LEDNETWFLight'>) sets invalid supported color modes {<ColorMode.BRIGHTNESS: 'brightness'>, <ColorMode.COLOR_TEMP: 'color_temp'>, <ColorMode.HS: 'hs'>}, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/raulgbcr/lednetwf_ble/issues
```

This means we need to port everything to using HS colorspaces instead of RGB.

I expect this is because it will remove the need to track colour and brightness separately.  It makes sense but it will be quite a significant change.

### PR DESCRIPTION
**Pull request by raulgbcr**
Should fix #22

### CODE REVIEW

**Comment by raulgbcr** [comment]
@8none1 mind checking on your end and see if the errors pop up? I have been running this for a while and haven't seen them come back

**Comment by 8none1** [comment]
Sorry for the late reply. I’ll take a look this week.

**Comment by raulgbcr** [comment]
Soooooo, I'm just gonna go ahead and merge this, have been using it for some time and didn't see the message reappear.

**Comment by 8none1** [comment]
Sorry for being so quiet. I’ve started a new job and have less time at the moment for hobbies. I’ll be back!

**Comment by raulgbcr** [comment]
> Sorry for being so quiet. I’ve started a new job and have less time at the moment for hobbies. I’ll be back!

No worries!! First things first! Don't ever think this is an obligation of any kind, we all have our things, and time + mood isn't always there ;)

**Pull request merged**
