### PR TITLE
Add support for configuring light strips and new types of strip

### PR DESCRIPTION
**Pull request by 8none1**
Fixes: #18 

I totally forgot to open the PR.  I've been running this for what seems like ages now and it feels solid to me.
Time to test in production!

### CODE REVIEW

**Comment by 8none1** [comment]
I had to resolve a bunch of merge conflicts by hand, I'm about 80% sure that it's OK, but I should test a bit more thoroughly first.

**Review by raulgbcr — APPROVED** [review]
I've been using it for some time too and haven't seen anything weird, feel free to merge and bump the version!!

**Comment by raulgbcr** [comment]
Thanks again!!!

**Comment by 8none1** [comment]
Ok, merging to main and then I will test before making a new release.

**Pull request merged**
